[workspace]
members = [
  "agentflow-core", 
  "agentflow-nodes",
#  "agentflow-config",
  "agentflow-llm", 
  "agentflow-cli",
  "agentflow-mcp",
  "agentflow-agents",
#   "agentflow-agents/agents/paper_assistant",
]
resolver = "2"