[workspace]
members = ["agentflow-core"]
resolver = "2"

[package]
name = "agentflow"
version = "0.1.0"
edition = "2021"
authors = ["AgentFlow Contributors"]
description = "A high-performance LLM framework inspired by PocketFlow"
repository = "https://github.com/agentflow/agentflow"
license = "MIT"
keywords = ["llm", "ai", "workflow", "agent", "mcp"]
categories = ["development-tools", "web-programming"]

[features]
default = []
observability = ["agentflow-core/observability"]

[dependencies]
agentflow-core = { path = "agentflow-core" }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
