{{- if and (not .Values.existingSecret) (or .Values.secretEnv.DATABASE_URL .Values.secretEnv.AGENTFLOW_API_TOKEN) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentflow.fullname" . }}
  labels:
    {{- include "agentflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secretEnv.DATABASE_URL }}
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}
  {{- end }}
  {{- if .Values.secretEnv.AGENTFLOW_API_TOKEN }}
  AGENTFLOW_API_TOKEN: {{ .Values.secretEnv.AGENTFLOW_API_TOKEN | quote }}
  {{- end }}
{{- end }}
