{{- if and (not .Values.existingSecret) .Values.secretEnv.DATABASE_URL -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentflow.fullname" . }}
  labels:
    {{- include "agentflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}
{{- end }}
