pub mod agent;
pub mod audio;
pub mod backup;
pub mod cleanup;
pub mod config;
pub mod doctor;
pub mod eval;
#[cfg(any(not(feature = "plugin"), not(feature = "rag")))]
pub mod feature_unavailable;
pub mod harness;
pub mod image;
pub mod llm;
pub mod marketplace;
pub mod mcp;
pub mod memory;
#[cfg(feature = "plugin")]
pub mod plugin;
pub mod rag;
pub mod repl;
pub mod restore;
pub mod serve;
pub mod skill;
pub mod trace;
pub mod workflow;
