{{- if and (not .Values.existingSecret) (or .Values.secretEnv.DATABASE_URL .Values.secretEnv.YANSHI_API_TOKEN) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yanshi.fullname" . }}
  labels:
    {{- include "yanshi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secretEnv.DATABASE_URL }}
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}
  {{- end }}
  {{- if .Values.secretEnv.YANSHI_API_TOKEN }}
  YANSHI_API_TOKEN: {{ .Values.secretEnv.YANSHI_API_TOKEN | quote }}
  {{- end }}
{{- end }}
