[package]
name = "agentflow-nodes"
version = "0.1.0"
edition = "2021"
authors = ["yuxuetr"]
description = "Built-in node implementations for AgentFlow workflows"
license = "MIT"
keywords = ["ai", "workflow", "nodes", "llm"]
categories = ["development-tools"]

[features]
default = ["llm", "http", "file", "template"]
llm = []
http = ["reqwest"]
file = []
template = ["handlebars"]
batch = []
conditional = []
factories = []

[dependencies]
# Core dependency - all nodes build on top of agentflow-core
agentflow-core = { path = "../agentflow-core" }

# LLM integration - required for real model execution
agentflow-llm = { path = "../agentflow-llm" }

# Removed: agentflow-config dependency to break circular dependency

# HTTP client for HTTP node
reqwest = { version = "0.11", features = ["json"], optional = true }

# Template engine for template node
handlebars = { version = "4.0", optional = true }

# Core serialization and async support
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Utilities
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"

# MarkMap and Arxiv node dependencies
flate2 = "1.0"
tar = "0.4"
regex = "1.0"

[dev-dependencies]
tokio-test = "0.4"

# Examples demonstrating real LLM model calling
[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "basic_llm_example"
path = "examples/basic_llm_example.rs"

[[example]]
name = "advanced_llm_example" 
path = "examples/advanced_llm_example.rs"

[[example]]
name = "multimodal_llm_example"
path = "examples/multimodal_llm_example.rs"

[[example]]
name = "structured_response_example"
path = "examples/structured_response_example.rs"

[[example]]
name = "parameter_showcase"
path = "examples/parameter_showcase.rs"

[[example]]
name = "model_compatibility_example"
path = "examples/model_compatibility_example.rs"

[[example]]
name = "fixed_enhanced_llm_example"
path = "examples/fixed_enhanced_llm_example.rs"

[[example]]
name = "multimodal_base64_example"
path = "examples/multimodal_base64_example.rs"

[[example]]
name = "multimodal_http_example"
path = "examples/multimodal_http_example.rs"

[[example]]
name = "mixed_image_sources_example"
path = "examples/mixed_image_sources_example.rs"
[[example]]
name = "claude_models_test"
path = "examples/claude_models_test.rs"

[[example]]
name = "debug_env_test"
path = "examples/debug_env_test.rs"

[[example]]
name = "direct_provider_test"
path = "examples/direct_provider_test.rs"

[[example]]
name = "claude_comprehensive_test" 
path = "examples/claude_comprehensive_test.rs"

[[example]]
name = "markmap_example"
path = "examples/markmap_example.rs"

[[example]]
name = "arxiv_example"
path = "examples/arxiv_example.rs"
